spring.application.name=customer-service
server.port=8081
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/customer?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysqlroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway (Since your logs show Flyway is active)
spring.flyway.enabled=true

# Eureka client settings
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html