spring.application.name=order-service
server.port=8084

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysqlroot

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Kafka Producer Config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Consumer Config (To listen for confirmation/rejection)
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trusted packages (Crucial for receiving DTOs from event-service)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.order_service.dto,com.event_service.dto
spring.kafka.producer.properties.spring.json.type.mapping=orderPlaced:com.order_service.dto.OrderPlacedEvent,orderConfirmed:com.order_service.dto.OrderConfirmedEvent,orderRejected:com.order_service.client.OrderRejectedEvent
spring.kafka.consumer.properties.spring.json.type.mapping=orderPlaced:com.order_service.dto.OrderPlacedEvent,orderConfirmed:com.order_service.dto.OrderConfirmedEvent,orderRejected:com.order_service.client.OrderRejectedEvent
# Change the value-deserializer to the ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
# Tell the wrapper to use JsonDeserializer internally
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer