spring.application.name=event-service
server.port=8083

# MySQL Connection
spring.datasource.url=jdbc:mysql://event-db:3306/event_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Kafka Consumer Config
spring.kafka.bootstrap-servers=kafka-broker:9092
spring.kafka.consumer.group-id=event-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Kafka Producer Config (Needed to send the rejection message)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Tell Flyway to only look in the 'event' sub-folder
spring.flyway.locations=classpath:db/migration/event

spring.kafka.producer.properties.spring.json.type.mapping=orderPlaced:com.event_service.dto.OrderPlacedEvent,orderConfirmed:com.event_service.dto.OrderConfirmedEvent,orderRejected:com.event_service.client.OrderRejectedEvent
# Trusted packages for JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.order_service.dto,com.event_service.dto,com.event_service.client
spring.kafka.consumer.properties.spring.json.type.mapping=orderPlaced:com.event_service.dto.OrderPlacedEvent,orderConfirmed:com.event_service.dto.OrderConfirmedEvent,orderRejected:com.event_service.client.OrderRejectedEvent

# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html